services:
  # 1. 메인 데이터베이스 (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: twitter_postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. 빠른 저장소 (Redis)
  redis:
    image: redis:alpine
    container_name: twitter_redis
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning

  # 3. 메시지 큐 (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: twitter_rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672" # 서비스들이 통신하는 포트
      - "${RABBITMQ_MANAGEMENT_PORT}:15672" # 우리가 눈으로 보는 관리자 웹 페이지 포트
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  # (선택사항) DB를 쉽게 눈으로 보는 도구 (Adminer)
  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  postgres_data:
