services:
  postgres:
    image: postgres:15-alpine
    container_name: test_twitter_postgres
    ports:
      - '${TEST_POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

  # 빠른 저장소 (Redis)
  redis:
    image: redis:alpine
    container_name: test_twitter_redis
    ports:
      - '${TEST_REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning

  # 메시지 큐 (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: test_twitter_rabbitmq
    ports:
      - '${TEST_RABBITMQ_PORT}:5672' # 서비스들이 통신하는 포트
      - '${TEST_RABBITMQ_MANAGEMENT_PORT}:15672' # 우리가 눈으로 보는 관리자 웹 페이지 포트
    environment:
      RABBITMQ_DEFAULT_USER: ${TEST_RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${TEST_RABBITMQ_DEFAULT_PASS}

  # (선택사항) DB를 쉽게 눈으로 보는 도구 (Adminer)
  adminer:
    image: adminer
    container_name: test_twitter_adminer
    restart: always
    ports:
      - '${TEST_ADMINER_PORT}:8080'

volumes:
  test_postgres_data:
